name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Minimal steps or code snippet to reproduce the issue.
      placeholder: |
        1. Create a client with `ZenMoneyBlocking::builder()...`
        2. Call `client.sync()`
        3. Observe error: ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened. Include error messages or stack traces if applicable.
    validations:
      required: true

  - type: input
    id: crate-version
    attributes:
      label: Crate version
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: rust-version
    attributes:
      label: Rust version
      description: Output of `rustc --version`.
      placeholder: "rustc 1.93.0 (..."
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other relevant information (feature flags used, storage backend, etc.).
    validations:
      required: false
